### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bhushan23**

### CODE REVIEW

**Comment by bhushan23** [comment]
@yuhuayc can we merge this?

**Comment by yuhuayc** [comment]
Hi, why do we want to merge this?

**Comment by bhushan23** [comment]
because instructions are invalid
```
cd $FRCN_ROOT/lib
./tools/train_net.py --gpu {GPU_ID} --solver models/da_faster_rcnn/solver.prototxt --weights data/imagenet_models/VGG16.v2.caffemodel --imdb voc_2007_trainval --iters  {NUM_ITER}  --cfg  {CONFIGURATION_FILE}
```
When you go to lib you need ../tools and not ./tools

are maybe just change it by yourself

**Comment by yuhuayc** [comment]
Right! I will change it according to your suggestion. Thanks for the help :)

**Pull request closed without merging**
